# parses croc_pkg.sv and wl_pkg.sv to extract Wakelet memory addresses
# and appends them to sw/include/config.h
#
# usage: python3 gen_config.py

import re
import os
import sys 

#define paths 

CROC_PKG = "../rtl/croc_pkg.sv"
WL_PKG = "../.bender/git/checkouts/wakelet-cee6ed1deea451c2/hw/wl_pkg.sv"
OUT_FILE = "config.h"


# helpers
 
def read_file(path):
    if not os.path.exists(path):
        print(f"ERROR: Cannot find {path}", file=sys.stderr)
        sys.exit(1)
    with open(path) as f:
        return f.read()
 
def parse_sv_value(raw):
    """Convert SV literal to Python int. Handles hex, decimal, binary, underscores."""
    raw = raw.strip().replace("_", "")
    m = re.match(r"(?:\d+)?'h([0-9a-fA-F]+)", raw)
    if m:
        return int(m.group(1), 16)
    m = re.match(r"(?:\d+)?'d(\d+)", raw)
    if m:
        return int(m.group(1))
    m = re.match(r"(?:\d+)?'b([01]+)", raw)
    if m:
        return int(m.group(1), 2)
    m = re.match(r"^(\d+)$", raw)
    if m:
        return int(m.group(1))
    return None
 
def extract_localparam(content, name):
    """Extract a localparam value by name from SV source."""
    pattern = rf"localparam\b[^;]*?\b{re.escape(name)}\s*=\s*([^;]+);"
    m = re.search(pattern, content, re.DOTALL)
    if not m:
        return None
    return parse_sv_value(m.group(1).strip())
 
def extract_addr_map_entry(content, idx_name):
    """Extract start_addr for a given idx name from an SV address map."""
    pattern = rf"idx\s*:\s*{re.escape(idx_name)}\s*,\s*start_addr\s*:\s*([^,}}]+)"
    m = re.search(pattern, content)
    if not m:
        return None
    return parse_sv_value(m.group(1).strip())
 

#actual work 
# Extract addresses from SV packages

croc = read_file(CROC_PKG)
wl   = read_file(WL_PKG)

base_address = extract_localparam(wl, "BaseAddress")
if base_address is None:
    base_address = 0  # defaults to '0

#added new
def extract_mem_offset(content, name):
    pattern = rf"\b{re.escape(name)}\s*=\s*BaseAddress\s*\+\s*([^;]+);"
    m = re.search(pattern, content)
    if not m:
        return None
    return parse_sv_value(m.group(1).strip())

instr_mem_offset = extract_mem_offset(wl, "InstrMemBaseAddr")
data_mem_offset  = extract_mem_offset(wl, "DataMemBaseAddr")

instr_mem_base = base_address + instr_mem_offset
data_mem_base  = base_address + data_mem_offset
 
user_base = extract_addr_map_entry(croc, "XbarUser")
if user_base is None:
    print("ERROR: Could not extract XbarUser from croc_pkg.sv", file=sys.stderr)
    sys.exit(1)
 
#instr_mem_base = extract_localparam(wl, "InstrMemBaseAddr")
#if instr_mem_base is None:
    #print("ERROR: Could not extract InstrMemBaseAddr from wl_pkg.sv", file=sys.stderr)
    #sys.exit(1)
 
#data_mem_base = extract_localparam(wl, "DataMemBaseAddr")
#if data_mem_base is None:
    #print("ERROR: Could not extract DataMemBaseAddr from wl_pkg.sv", file=sys.stderr)
    #sys.exit(1)
 
wakelet_imem = user_base + instr_mem_base
wakelet_dmem = user_base + data_mem_base
 
#append address
wakelet_block = f"""
// Wakelet user domain (via OBI-to-AXI-Lite bridge)
// Auto-generated by gen_config.py -- do not edit manually
// croc_pkg::UserBaseAddr({user_base:#010x}) + wl_pkg::InstrMemBaseAddr({instr_mem_base:#010x})
#define WAKELET_IMEM_ADDR       {wakelet_imem:#010x}
// croc_pkg::UserBaseAddr({user_base:#010x}) + wl_pkg::DataMemBaseAddr({data_mem_base:#010x})
#define WAKELET_DMEM_ADDR       {wakelet_dmem:#010x}
"""
 
# Read existing config.h
with open(OUT_FILE, "r") as f:
    existing = f.read()
 
# Remove any previous Wakelet block to avoid duplicates on re-run
existing = re.sub(
    r"\n// Wakelet user domain.*?#define WAKELET_DMEM_ADDR[^\n]*\n",
    "",
    existing,
    flags=re.DOTALL
)
 
# Append new Wakelet block
with open(OUT_FILE, "w") as f:
    f.write(existing.rstrip("\n") + "\n" + wakelet_block)
 
print(f"Updated {OUT_FILE}")
print(f"  WAKELET_IMEM_ADDR = {wakelet_imem:#010x}")
print(f"  WAKELET_DMEM_ADDR = {wakelet_dmem:#010x}")